AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GlaDos Intelligence API - Serverless Backend

Resources:
  GlaDosFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image  # Change this from CodeUri/Runtime
      Architectures:
        - x86_64
      MemorySize: 3008
      Timeout: 60
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
      Events:
        GlaDosApi:
          Type: HttpApi # Better performance and easier CORS than 'Api'
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile

Parameters:
  DatabaseUrl:
    Type: String
    Description: Connection string for supabase
